### ISSUE TITLE
Can't upload contact photo

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1442]
This was reported by an exhibit curator and I've confirmed the problem, both in that curator's exhibit and my own text exhibit. When you try to upload an image for the About page contact the image doesn't load and never appears in the crop box. 

It appears to be a mixed-content issue. I get this error in the console:

> Mixed Content: The page at 'https://exhibits.stanford.edu/gary-testing/about/contacts/new' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://exhibits.stanford.edu/images/5945/info.json'. This request has been blocked; the content must be served over HTTPS.

**Comment by mejackreed** [comment]
@ggeisler I think this was fixed upstream in https://github.com/projectblacklight/spotlight/pull/2217 and released yesterday in Spotlight v2.11.0. This should get updated on Monday with the normal dependency update cycle unless we update sooner.

**Comment by ggeisler** [comment]
Great, that should be fine. Thanks!

**Comment by mejackreed** [comment]
Resolved in #1443

**Comment by caaster** [comment]
This issue is not resolved, unfortunately - still can't upload contact photo.

**Comment by camillevilla** [comment]
This issue should be resolved by #2243 and upgrading Exhibits to a new version of Spotlight.
