### ISSUE TITLE
Mirador showing on the Reference show page

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#720]
We're seeing Mirador showing up on the Reference show page. Right now it's working in stage, but not production. I think it was related to the custom manifest pattern being set. Is that correct @mejackreed ?

**Comment by mejackreed** [comment]
Yep it should be fixed now. We just haven't created a release and shipped to prod.

**Comment by drh-stanford** [comment]
I'm still seeing this in exhibits-stage when I set a custom manifest pattern. Do you have a commit sha or a ticket number that fixes this issue?

**Comment by drh-stanford** [comment]
Pushed up the latest `master` to stage and verified that this is fixed.
